<?php
/**
 * Migration 007 Part 1: Rebuild schema + marga master list
 * Sumber: Wikipedia "Daftar marga Batak" (350+), H.B. Situmorang (1983)
 */

$pdo = new PDO('mysql:unix_socket=/opt/lampp/var/mysql/mysql.sock;dbname=tarombo', 'root', 'root');
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

echo "=== MIGRATION 007 Part 1: SCHEMA + MARGA ===\n\n";

// DROP
$pdo->exec("SET FOREIGN_KEY_CHECKS = 0");
$pdo->exec("DROP TABLE IF EXISTS marga_alias");
$pdo->exec("DROP TABLE IF EXISTS marga_sub_suku");
$pdo->exec("DROP TABLE IF EXISTS marga");
$pdo->exec("DROP TABLE IF EXISTS silsilah_mitolologis");
$pdo->exec("SET FOREIGN_KEY_CHECKS = 1");

// CREATE silsilah_mitolologis
$pdo->exec("CREATE TABLE silsilah_mitolologis (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(200) NOT NULL,
    jenis_kelamin ENUM('L','P') DEFAULT 'L',
    orang_tuan_id INT NULL,
    generasi_ke INT NOT NULL,
    peran TEXT NULL,
    pasangan_nama TEXT NULL,
    info_perkawinan TEXT NULL,
    marga_turunan VARCHAR(200) NULL,
    wilayah VARCHAR(100) NULL,
    sumber VARCHAR(200) NULL DEFAULT 'W.M. Hutagalung (1926)',
    tingkat_kepastian ENUM('tinggi','sedang','rendah') DEFAULT 'tinggi',
    catatan TEXT NULL,
    FOREIGN KEY (orang_tuan_id) REFERENCES silsilah_mitolologis(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

// CREATE marga
$pdo->exec("CREATE TABLE marga (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(200) NOT NULL UNIQUE,
    sub_suku VARCHAR(100) NULL,
    kelompok_marga VARCHAR(100) NULL,
    marga_induk_id INT NULL,
    silsilah_node_id INT NULL,
    keterangan TEXT NULL,
    sumber VARCHAR(200) NULL DEFAULT 'Wikipedia - Daftar marga Batak',
    FOREIGN KEY (marga_induk_id) REFERENCES marga(id) ON DELETE SET NULL,
    FOREIGN KEY (silsilah_node_id) REFERENCES silsilah_mitolologis(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

// CREATE marga_sub_suku
$pdo->exec("CREATE TABLE marga_sub_suku (
    id INT AUTO_INCREMENT PRIMARY KEY,
    marga_id INT NOT NULL,
    sub_suku VARCHAR(100) NOT NULL,
    is_native TINYINT(1) DEFAULT 0,
    keterangan TEXT NULL,
    FOREIGN KEY (marga_id) REFERENCES marga(id) ON DELETE CASCADE,
    UNIQUE KEY uq_marga_suku (marga_id, sub_suku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

// CREATE marga_alias
$pdo->exec("CREATE TABLE marga_alias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    marga_id INT NOT NULL,
    alias_nama VARCHAR(200) NOT NULL,
    sub_suku VARCHAR(100) NULL,
    keterangan TEXT NULL,
    sumber VARCHAR(200) NULL,
    FOREIGN KEY (marga_id) REFERENCES marga(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");

echo "Tables created.\n";

// ============================================
// MARGA MASTER LIST
// ============================================
echo "Inserting marga master list...\n";

$margaData = [
    // A
    ['Ajartambun','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Ambarita','Toba','Silau Raja',NULL,NULL],
    ['Angkat','Pakpak',NULL,NULL,NULL],
    ['Angkat Singkapal','Pakpak',NULL,'Angkat',NULL],
    ['Aritonang','Toba','Lontung',NULL,NULL],
    ['Aruan','Toba','Naisuanon',NULL,'Submarga Si Paet Tua'],
    // B
    ['Babiat','Mandailing',NULL,NULL,'Keturunan Si Raja Babiat. Marga Bayoangin'],
    ['Babo','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Bako','Pakpak',NULL,NULL,'Alias Naibaho di Pakpak'],
    ['Bancin','Pakpak',NULL,NULL,NULL],
    ['Banjarnahor','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Banuarea','Pakpak',NULL,NULL,'Alias Bunurea'],
    ['Bakkara','Pakpak',NULL,NULL,NULL],
    ['Bariba','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Baringbing','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Barotbot','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Baruara','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan / Tambunan'],
    ['Barus','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Batuara','Toba','Naiambaton',NULL,'Submarga Nainggolan / Mahulae'],
    ['Batubara','Toba','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Baumi','Toba','Lontung',NULL,'Submarga Siregar'],
    ['Bayu','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Benjerang','Karo',NULL,'Perangin-angin','Submarga Perangin-angin'],
    ['Berampu','Pakpak',NULL,NULL,'Submarga Simbolon (Si Onom Hudon)'],
    ['Beras','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Berasa','Pakpak',NULL,NULL,'Submarga Ompu Bada / Si Onom Kodin'],
    ['Beringin','Pakpak',NULL,NULL,'Submarga Ompu Bada / Si Onom Kodin'],
    ['Berutu','Pakpak',NULL,NULL,'Submarga Simbolon (Si Onom Hudon)'],
    ['Barutu','Pakpak',NULL,NULL,'Alias Berutu'],
    ['Bintang','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Boangmanalu','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Manalu'],
    ['Bondar','Toba','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Bondong','Karo',NULL,'Tarigan','Submarga Tarigan'],
    ['Boliala','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Brahmana','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Buaton','Toba','Naiambaton',NULL,'Submarga Nainggolan'],
    ['Bukit','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Buniaji','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Busuk','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Butarbutar','Toba','Nairasaon',NULL,'Submarga Raja Mardopang'],
    // C
    ['Capah','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Cibro','Pakpak',NULL,NULL,NULL],
    ['Colia','Karo',NULL,'Sembiring','Submarga Sembiring'],
    // D
    ['Dajawak','Simalungun',NULL,'Saragih','Submarga Saragih'],
    ['Dalimunthe','Angkola',NULL,'Munte','Alias Munte di Angkola/Mandailing'],
    ['Damanik','Simalungun',NULL,NULL,'Marga induk Simalungun. Asal: Manik (Silau Raja)'],
    ['Damunthei','Simalungun',NULL,'Saragih','Submarga Saragih'],
    ['Dasalak','Simalungun',NULL,'Saragih','Submarga Saragih'],
    ['Dasopang','Angkola',NULL,NULL,NULL],
    ['Daulay','Mandailing',NULL,NULL,NULL],
    ['Debataraja','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Simamora'],
    ['Depari','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Doloksaribu','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Dongoran','Toba','Lontung',NULL,'Submarga Siregar. Juga di Angkola'],
    // G
    ['Gajah','Pakpak',NULL,NULL,'Submarga Ompu Bada / Si Onom Kodin'],
    ['Gajamanik','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Ganagana','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Garamata','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Ginting','Karo',NULL,NULL,'Marga induk Karo'],
    ['Giringging','Toba','Naiambaton',NULL,'Submarga Munte Tua'],
    ['Gerneng','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Girsang','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba'],
    ['Gorat','Toba','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Gultom','Toba','Lontung',NULL,'Submarga Pandiangan'],
    ['Gurning','Toba','Silau Raja',NULL,'Putra Silau Raja'],
    ['Gurukinayan','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Gurusinga','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Gurupatih','Karo',NULL,'Ginting','Submarga Ginting'],
    // H
    ['Habeahan','Toba','Limbong',NULL,'Submarga Limbong. Juga di Borbor'],
    ['Harahap','Mandailing','Borbor',NULL,'Submarga Datu Taladibabana (Borbor)'],
    ['Harianja','Toba','Lontung',NULL,'Submarga Pandiangan'],
    ['Haromunthe','Simalungun',NULL,'Munte','Alias Munte di Simalungun'],
    ['Hasibuan','Toba','Naisuanon',NULL,'Submarga Si Raja Sobu'],
    ['Hasugian','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Hutabalian','Toba','Naiambaton',NULL,'Submarga Nainggolan'],
    ['Hutabarat','Toba','Naisuanon',NULL,'Submarga Si Raja Sobu'],
    ['Hutagaol','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Hutagalung','Toba','Naisuanon',NULL,'Submarga Si Raja Sobu'],
    ['Hutahaean','Toba','Naisuanon',NULL,'Submarga Si Paet Tua'],
    ['Hutajulu','Toba','Naisuanon',NULL,'Submarga Si Paet Tua'],
    ['Hutanamora','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Hutapea','Toba','Naisuanon',NULL,'Submarga Si Paet Tua & Si Raja Sobu'],
    ['Hutasoit','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Sihombing'],
    ['Hutasuhut','Mandailing','Borbor',NULL,'Submarga Datu Pulungan (Borbor)'],
    ['Hutatoruan','Toba','Naisuanon',NULL,'Submarga Si Raja Sobu'],
    ['Hutauruk','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    // J
    ['Jadibata','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Jampang','Karo',NULL,'Tarigan','Submarga Tarigan'],
    ['Jawak','Karo',NULL,'Ginting','Submarga Ginting'],
    // K
    ['Kaban','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Kabeaken','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Kacaribu','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Kaloko','Pakpak',NULL,NULL,'Alias Sihaloho di Pakpak'],
    ['Keling','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Keloko','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Kembaren','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Kemit','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Ketaren','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Kombih','Pakpak',NULL,NULL,NULL],
    ['Kudadiri','Pakpak',NULL,NULL,NULL],
    // L
    ['Lembeng','Pakpak',NULL,NULL,'Alias Limbong di Pakpak'],
    ['Limbong','Toba','Limbong',NULL,'Marga induk Limbong Mulana'],
    ['Lingga','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan. Juga di Karo'],
    ['Lintang','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Lubis','Mandailing','Borbor',NULL,'Submarga Datu Pulungan (Borbor). Marga besar Mandailing'],
    ['Lumbanbatu','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Lumbangaol','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Lumbannahor','Toba','Lontung',NULL,'Submarga Situmorang'],
    ['Lumbanpea','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan / Tambunan'],
    ['Lumbanraja','Toba','Naiambaton',NULL,'Submarga Nainggolan'],
    ['Lumbansiantar','Toba','Naiambaton',NULL,'Submarga Nainggolan'],
    ['Lumbantobing','Toba','Naisuanon',NULL,'Submarga Si Raja Sobu'],
    ['Lumbantoruan','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Sihombing'],
    ['Lumbantungkup','Toba','Naiambaton',NULL,'Submarga Nainggolan'],
    // M
    ['Maha','Toba','Naisuanon',NULL,'Submarga Si Raja Huta Lima'],
    ['Maharaja','Toba','Naiambaton',NULL,'Submarga Simbolon Tua'],
    ['Mahulae','Toba','Naiambaton',NULL,'Submarga Nainggolan / Batuara'],
    ['Malau','Toba','Silau Raja',NULL,'Putra sulung Silau Raja'],
    ['Manalu','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Simamora'],
    ['Manihuruk','Toba','Naiambaton',NULL,'Submarga Munte Tua'],
    ['Manik','Toba','Silau Raja',NULL,'Putra Silau Raja'],
    ['Manik Kecupak','Pakpak',NULL,NULL,'Submarga Ompu Bada di Pakpak'],
    ['Manurung','Toba','Nairasaon',NULL,'Submarga Raja Mangatur'],
    ['Marbun','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Mardia','Mandailing',NULL,'Rangkuti','Submarga Rangkuti'],
    ['Marpaung','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Matanari','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Matondang','Angkola','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Meka','Pakpak',NULL,'Marbun','Submarga Marbun di Pakpak'],
    ['Milala','Karo',NULL,'Sembiring','Submarga Sembiring / Meliala'],
    ['Meliala','Karo',NULL,'Sembiring','Submarga Sembiring. Juga di Toba (Si Raja Huta Lima)'],
    ['Muham','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Mungkur','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Munte','Toba','Naiambaton',NULL,'Submarga Munte Tua'],
    ['Munthe','Simalungun',NULL,'Munte','Alias Munte di Simalungun'],
    // N
    ['Nababan','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Sihombing'],
    ['Nadapdap','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Nadeak','Toba','Naiambaton',NULL,'Submarga Saragi Tua'],
    ['Nagur','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Nahampun','Toba','Naiambaton',NULL,'Submarga Simbolon Tua'],
    ['Naibaho','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Naiborhu','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Nainggolan','Toba','Naiambaton',NULL,'Marga induk dari Toga Nainggolan'],
    ['Naipospos','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Napitu','Toba','Naiambaton',NULL,'Submarga Tamba Tua'],
    ['Napitupulu','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Nasution','Mandailing',NULL,NULL,'Marga besar Mandailing'],
    // O
    ['Ompusunggu','Toba','Lontung',NULL,'Submarga Aritonang'],
    // P
    ['Padang','Toba','Lontung',NULL,'Submarga Situmorang'],
    ['Padang Batanghari','Toba','Lontung',NULL,'Submarga Situmorang'],
    ['Pakpahan','Toba','Lontung',NULL,'Submarga Pandiangan'],
    ['Pandebayang','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Pane','Toba','Nairasaon',NULL,'Submarga Sitorus'],
    ['Pangaribuan','Toba','Naisuanon',NULL,'Submarga Si Paet Tua'],
    ['Panggabean','Toba','Naisuanon',NULL,'Submarga Si Raja Sobu'],
    ['Panjaitan','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Parapat','Toba','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Pardede','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Pardosi','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan & Si Raja Huta Lima'],
    ['Parhusip','Toba','Naiambaton',NULL,'Submarga Nainggolan'],
    ['Parmata','Simalungun',NULL,'Saragih','Submarga Saragih'],
    ['Paroka','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Parinduri','Mandailing',NULL,'Rangkuti','Submarga Rangkuti'],
    ['Pasaribu','Toba','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Pase','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Pasei','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Pasi','Pakpak',NULL,NULL,'Submarga Simbolon (Si Onom Hudon)'],
    ['Pekan','Karo',NULL,'Tarigan','Submarga Tarigan'],
    ['Pelawi','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Penarik','Pakpak',NULL,'Perangin-angin','Submarga Perangin-angin'],
    ['Perangin-angin','Karo',NULL,NULL,'Marga induk Karo'],
    ['Pinayungan','Toba','Naiambaton',NULL,'Submarga Simbolon Tua'],
    ['Pintubatu','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Pohan','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Porti','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Pulungan','Mandailing','Borbor',NULL,'Submarga Datu Pulungan (Borbor)'],
    ['Purba','Simalungun',NULL,NULL,'Marga induk Simalungun. Juga di Toba/Karo'],
    // R
    ['Rambe','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Simamora'],
    ['Rajagukguk','Toba','Lontung',NULL,'Submarga Aritonang'],
    ['Rampogos','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Rangkuti','Mandailing','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Rih','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Ritonga','Toba','Lontung',NULL,'Submarga Siregar'],
    ['Rumabutar','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Manalu'],
    ['Rumagorga','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Manalu'],
    ['Rumahole','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Manalu'],
    ['Rumahorbo','Toba','Naiambaton',NULL,'Submarga Tamba Tua'],
    ['Rumaijuk','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Manalu'],
    ['Rumapea','Toba','Lontung',NULL,'Submarga Situmorang'],
    ['Rumasingap','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Rumasondi','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    // S
    ['Sagala','Toba','Sagala',NULL,'Marga induk Sagala Raja'],
    ['Saing','Toba','Naiambaton',NULL,'Submarga Saragi Tua'],
    ['Sambo','Toba','Naisuanon',NULL,'Submarga Si Raja Huta Lima'],
    ['Samosir','Toba','Lontung',NULL,'Submarga Pandiangan'],
    ['Samura','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Saraan','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Saragi','Toba','Naiambaton',NULL,'Submarga Saragi Tua'],
    ['Saragih','Simalungun',NULL,NULL,'Marga induk Simalungun. Asal: Saragi Tua'],
    ['Sarasan','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Saruksuk','Toba','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Sarumpaet','Toba','Naisuanon',NULL,'Submarga Si Paet Tua'],
    ['Sehun','Pakpak',NULL,NULL,NULL],
    ['Sekali','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Sembiring','Karo',NULL,NULL,'Marga induk Karo. Asal: Si Raja Huta Lima (Toba)'],
    ['Seragih','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Siadari','Toba','Naiambaton',NULL,'Submarga Tamba Tua'],
    ['Siagian','Toba','Lontung',NULL,'Submarga Siregar / Si Bagot Ni Pohan'],
    ['Siahaan','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Siallagan','Toba','Naiambaton',NULL,'Submarga Tamba Tua'],
    ['Sianipar','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Sianturi','Toba','Lontung',NULL,'Submarga Simatupang'],
    ['Sibagariang','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Sibarani','Toba','Naisuanon',NULL,'Submarga Si Paet Tua'],
    ['Sibero','Karo',NULL,'Tarigan','Submarga Tarigan'],
    ['Siboro','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Simamora'],
    ['Sibuea','Toba','Naisuanon',NULL,'Submarga Si Paet Tua'],
    ['Siburian','Toba','Lontung',NULL,'Submarga Simatupang'],
    ['Sidauruk','Toba','Naiambaton',NULL,'Submarga Munte Tua'],
    ['Sidabalok','Simalungun',NULL,'Saragih','Submarga Saragih'],
    ['Sidabutar','Toba','Naiambaton',NULL,'Submarga Tamba Tua & Si Lahi Sabungan'],
    ['Sidabungke','Toba','Naiambaton',NULL,'Submarga Saragi Tua'],
    ['Sidadolog','Simalungun',NULL,'Purba','Submarga Purba'],
    ['Sidagambir','Simalungun',NULL,'Purba','Submarga Purba'],
    ['Sidagurgur','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Sidahambang','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Sidahapitu','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Sidahoro','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Sidalogan','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Sidapulou','Simalungun',NULL,'Saragih','Submarga Saragih'],
    ['Sidari','Toba','Lontung',NULL,'Submarga Pandiangan'],
    ['Sidasuha','Simalungun',NULL,'Purba','Submarga Purba'],
    ['Sidasuhut','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Sidebang','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Sigalingging','Toba','Naiambaton',NULL,'Submarga Munte Tua'],
    ['Sigiro','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Sigukguhi','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Manalu'],
    ['Sigumonrong','Simalungun',NULL,'Purba','Submarga Purba'],
    ['Sihala','Simalungun',NULL,'Purba','Submarga Purba'],
    ['Sihaloho','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Sihite','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Sihole','Toba','Limbong',NULL,'Submarga Limbong (Langgat Limbong)'],
    ['Sihombing','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba. Sihombing si Opat Ama'],
    ['Sihotang','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Sijabat','Toba','Naiambaton',NULL,'Submarga Tamba Tua'],
    ['Siketang','Pakpak',NULL,NULL,'Alias Sihotang di Pakpak'],
    ['Silaen','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan / Tampubolon'],
    ['Silaban','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Sihombing'],
    ['Silalahi','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan. Marga induk'],
    ['Silampuyang','Simalungun',NULL,'Saragih','Submarga Saragih'],
    ['Silangit','Karo',NULL,'Tarigan','Submarga Tarigan'],
    ['Sileang','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan / Sihite'],
    ['Silitonga','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Simaibang','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Simalango','Toba','Naiambaton',NULL,'Submarga Saragi Tua'],
    ['Simamora','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba'],
    ['Simandalahi','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Simangunsong','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Simanjorang','Toba','Lontung',NULL,'Submarga Sinaga'],
    ['Simanjuntak','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Simanullang','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Simanungkalit','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Simaremare','Toba','Lontung',NULL,'Submarga Aritonang'],
    ['Simargolang','Toba','Borbor',NULL,'Submarga Datu Taladibabana (Borbor)'],
    ['Simaringga','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Simarmata','Toba','Naiambaton',NULL,'Submarga Saragi Tua'],
    ['Simarsoit','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan / Sihotang'],
    ['Simatupang','Toba','Lontung',NULL,'Putra kelima Si Raja Lontung'],
    ['Simbolon','Toba','Naiambaton',NULL,'Putra sulung Nai Ambaton'],
    ['Simbulan','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Simorangkir','Toba','Naisuanon',NULL,'Submarga Si Raja Sobu'],
    ['Sinabariba','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Sinabang','Pakpak',NULL,NULL,NULL],
    ['Sinabutar','Pakpak',NULL,NULL,'Alias Sidabutar di Pakpak'],
    ['Sinaga','Toba','Lontung',NULL,'Putra kedua Si Raja Lontung'],
    ['Sinambela','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Sinamo','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Sinisuka','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Sinubulan','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Sinuhaji','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Sinukaban','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Sinukapar','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Sinulaki','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Sinulingga','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Sinupayung','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Sinuraya','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Sinusinga','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Sinurat','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Sipahutar','Toba','Borbor',NULL,'Submarga Datu Taladibabana (Borbor)'],
    ['Sipangkar','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Siampapaga','Toba','Naiambaton',NULL,'Submarga Nainggolan / Nahampun'],
    ['Sipardabuan','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan / Sihotang'],
    ['Sipayung','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Sipoldas','Simalungun',NULL,'Saragih','Submarga Saragih'],
    ['Sirait','Toba','Nairasaon',NULL,'Submarga Raja Mardopang'],
    ['Siregar','Toba','Lontung',NULL,'Putra ketujuh Si Raja Lontung'],
    ['Siringoringo','Toba','Lontung',NULL,'Submarga Situmorang'],
    ['Sitanggang','Toba','Naiambaton',NULL,'Submarga Munte Tua'],
    ['Sitakar','Pakpak',NULL,NULL,NULL],
    ['Sitepu','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Sitindaon','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Sihombing'],
    ['Sitinjak','Toba','Lontung',NULL,'Submarga Pandiangan'],
    ['Sitio','Toba','Naiambaton',NULL,'Submarga Munte Tua'],
    ['Sitohang','Toba','Lontung',NULL,'Submarga Situmorang'],
    ['Sitompul','Toba','Naisuanon',NULL,'Submarga Si Raja Sobu'],
    ['Sitopu','Pakpak',NULL,NULL,NULL],
    ['Sitorus','Toba','Nairasaon',NULL,'Submarga Raja Mardopang'],
    ['Situmeang','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Situmorang','Toba','Lontung',NULL,'Putra sulung Si Raja Lontung'],
    ['Situngkir','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Sola','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Solin','Toba','Lontung',NULL,'Submarga Situmorang'],
    ['Sorganimusu','Pakpak',NULL,NULL,NULL],
    ['Sorimunggu','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba / Manalu'],
    ['Sormin','Toba','Lontung',NULL,'Submarga Siregar'],
    ['Sugihen','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Suka','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Surbakti','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    // T
    ['Tamba','Toba','Naiambaton',NULL,'Putra kedua Nai Ambaton'],
    ['Tambak','Toba','Naisuanon',NULL,'Submarga Si Raja Sumba'],
    ['Tambun','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Tambunan','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Tampubolon','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Tampune','Karo',NULL,'Ginting','Submarga Ginting'],
    ['Tanjung','Toba','Borbor',NULL,'Submarga Datu Taladibabana (Borbor)'],
    ['Tarihoran','Toba','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Tegur','Karo',NULL,'Tarigan','Submarga Tarigan'],
    ['Tekang','Karo',NULL,'Sembiring','Submarga Sembiring'],
    ['Tendang','Pakpak',NULL,NULL,'Submarga Ompu Bada / Si Onom Kodin'],
    ['Tinambunan','Toba','Naiambaton',NULL,'Submarga Simbolon Tua'],
    ['Tinendung','Pakpak',NULL,NULL,'Submarga Simbolon (Si Onom Hudon)'],
    ['Togatorop','Toba','Lontung',NULL,'Submarga Simatupang'],
    ['Tomog','Simalungun',NULL,'Damanik','Submarga Damanik'],
    ['Tondang','Simalungun',NULL,'Purba','Submarga Purba'],
    ['Torbandolok','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan / Sihotang'],
    ['Torong','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Tua','Karo',NULL,'Tarigan','Submarga Tarigan'],
    ['Tumanggor','Toba','Naiambaton',NULL,'Submarga Simbolon Tua'],
    ['Turnip','Toba','Naiambaton',NULL,'Submarga Munte Tua'],
    ['Turutan','Toba','Naiambaton',NULL,'Submarga Simbolon Tua'],
    // U
    ['Ujung','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Ujungsaribu','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Usang','Simalungun',NULL,'Damanik','Submarga Damanik'],
    // Pasisi
    ['Ace','Pasisi',NULL,NULL,'Batak Pasisi (Pesisir)'],
    ['Badan','Pasisi',NULL,NULL,'Batak Pasisi (Pesisir)'],
    ['Chaniago','Pasisi',NULL,NULL,'Batak Pasisi (Pesisir). Asal Minang'],
    ['Malabu','Pasisi',NULL,NULL,'Batak Pasisi (Pesisir)'],
    ['Priaman','Pasisi',NULL,NULL,'Batak Pasisi (Pesisir). Asal Minang'],
    ['Rao','Pasisi',NULL,NULL,'Batak Pasisi (Pesisir)'],
    ['Saribu','Pasisi',NULL,NULL,'Batak Pasisi (Pesisir)'],
    ['Sibuaya','Pasisi',NULL,NULL,'Batak Pasisi (Pesisir)'],
    // Nasution sub-marga
    ['Nasution Bototan','Mandailing',NULL,'Nasution','Submarga Nasution'],
    ['Nasution Loncat','Mandailing',NULL,'Nasution','Submarga Nasution'],
    ['Nasution Tangga Ambeng','Mandailing',NULL,'Nasution','Submarga Nasution'],
    ['Nasution Simanggintir','Mandailing',NULL,'Nasution','Submarga Nasution'],
    ['Nasution Manggis','Mandailing',NULL,'Nasution','Submarga Nasution'],
    ['Nasution Jor','Mandailing',NULL,'Nasution','Submarga Nasution'],
    // Lubis sub-marga
    ['Lubis Hatonopan','Mandailing',NULL,'Lubis','Submarga Lubis'],
    ['Lubis Singasoro','Mandailing',NULL,'Lubis','Submarga Lubis'],
    // Tambahan
    ['Bangun','Karo',NULL,'Tarigan','Submarga Tarigan'],
    ['Barusa','Pakpak',NULL,NULL,NULL],
    ['Dapari','Pakpak',NULL,NULL,NULL],
    ['Daulae','Mandailing',NULL,NULL,NULL],
    ['Gajadiri','Pakpak',NULL,NULL,NULL],
    ['Hotmatua','Toba','Naisuanon',NULL,'Submarga Si Bagot Ni Pohan'],
    ['Karosekali','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Kombara','Karo',NULL,'Karo-karo','Submarga Karo-karo'],
    ['Lumbandolok','Toba','Naiambaton',NULL,'Submarga Nainggolan'],
    ['Mahabunga','Pakpak',NULL,NULL,NULL],
    ['Maliam','Pakpak',NULL,NULL,NULL],
    ['Martumpu','Pakpak',NULL,NULL,NULL],
    ['Mataniari','Toba','Naisuanon',NULL,'Submarga Si Raja Oloan'],
    ['Mismis','Toba','Naisuanon',NULL,'Submarga Si Raja Sobu'],
    ['Mukur','Toba','Naisuanon',NULL,'Submarga Toga Naipospos'],
    ['Pinem','Karo',NULL,'Perangin-angin','Submarga Perangin-angin'],
    ['Pospos','Angkola',NULL,NULL,'Alias Naipospos di Angkola'],
    ['Ramin','Pakpak',NULL,NULL,NULL],
    ['Sibabiat','Toba',NULL,NULL,'Alias Bayoangin/Babiat'],
    ['Sunge','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan / Tambunan'],
    ['Tambun Saribu','Toba','Naisuanon',NULL,'Submarga Si Lahi Sabungan'],
    ['Tangkar','Toba','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
    ['Tinendang','Toba','Borbor',NULL,'Submarga Datu Dalu (Borbor)'],
];

$insertMarga = $pdo->prepare("INSERT INTO marga (nama, sub_suku, kelompok_marga, keterangan, sumber) VALUES (?, ?, ?, ?, ?)");
$count = 0;
foreach ($margaData as $m) {
    try {
        $insertMarga->execute([$m[0], $m[1], $m[2], $m[4], 'Wikipedia - Daftar marga Batak; H.B. Situmorang (1983)']);
        $count++;
    } catch (PDOException $e) {
        if ($e->getCode() != 23000) throw $e;
    }
}
echo "Inserted {$count} marga.\n";

// Set marga_induk_id
$indukMap = [
    'Ginting' => ['Ajartambun','Babo','Beras','Capah','Gajamanik','Ganagana','Garamata','Gerneng','Gurukinayan','Gurusinga','Gurupatih','Jawak','Manihuruk','Matanari','Pase','Seragih','Sinisuka','Sinusinga','Sugihen','Suka','Tampune'],
    'Karo-karo' => ['Barus','Bukit','Hutanamora','Kaban','Kabeaken','Kacaribu','Kemit','Ketaren','Lintang','Paroka','Samura','Sekali','Simaringga','Simbulan','Sinubulan','Sinuhaji','Sinukaban','Sinulingga','Sinuraya','Sitepu','Surbakti','Torong','Karosekali','Kombara'],
    'Perangin-angin' => ['Benjerang','Penarik','Pinem'],
    'Sembiring' => ['Brahmana','Buniaji','Busuk','Colia','Keling','Keloko','Kembaren','Milala','Muham','Pandebayang','Pelawi','Sinukapar','Sinulaki','Sinupayung','Tekang','Meliala'],
    'Tarigan' => ['Bondong','Jampang','Pekan','Sibero','Silangit','Tegur','Tua','Bangun'],
    'Nasution' => ['Nasution Bototan','Nasution Loncat','Nasution Tangga Ambeng','Nasution Simanggintir','Nasution Manggis','Nasution Jor'],
    'Lubis' => ['Lubis Hatonopan','Lubis Singasoro'],
    'Damanik' => ['Bariba','Barotbot','Bayu','Nagur','Pasei','Rampogos','Rih','Sarasan','Sola','Tomog'],
    'Saragih' => ['Dajawak','Damunthei','Dasalak','Parmata','Sidabalok','Sidapulou','Silampuyang','Sipoldas'],
    'Purba' => ['Sidadolog','Sidagambir','Sidasuha','Sigumonrong','Sihala','Tondang'],
    'Sinaga' => ['Porti','Sidagurgur','Sidahambang','Sidahapitu','Sidahoro','Sidalogan','Sidasuhut','Simaibang','Simandalahi','Simanjorang'],
    'Sihombing' => ['Silaban','Lumbantoruan','Nababan','Hutasoit','Sitindaon'],
    'Manalu' => ['Rumabutar','Rumagorga','Rumahole','Rumaijuk','Sigukguhi','Sorimunggu','Boangmanalu'],
    'Angkat' => ['Angkat Singkapal'],
    'Munte' => ['Dalimunthe','Haromunthe','Munthe'],
    'Tambunan' => ['Baruara','Lumbanpea','Tambun Saribu','Sunge'],
    'Rangkuti' => ['Mardia','Parinduri'],
    'Marbun' => ['Meka'],
    'Siregar' => ['Dongoran','Ritonga','Sormin','Siagian','Baumi'],
    'Situmorang' => ['Lumbannahor','Siringoringo','Rumapea','Solin','Sitohang','Padang','Padang Batanghari'],
    'Nainggolan' => ['Batuara','Buaton','Hutabalian','Lumbanraja','Lumbansiantar','Lumbantungkup','Parhusip','Pusuk','Mahulae','Lumbandolok'],
    'Naibaho' => ['Bako'],
    'Sihotang' => ['Siketang','Simarsoit','Sipardabuan','Torbandolok'],
    'Sihite' => ['Sileang'],
    'Tamba' => ['Siallagan','Sidabutar','Sijabat','Siadari','Rumahorbo','Napitu'],
    'Saragi' => ['Simalango','Saing','Simarmata','Nadeak','Sidabungke'],
    'Simbolon' => ['Tinambunan','Tumanggor','Maharaja','Turutan','Nahampun','Pinayungan','Berampu','Berutu','Pasi','Tinendung'],
    'Munte Tua' => ['Sitanggang','Manihuruk','Sidauruk','Turnip','Sitio','Sigalingging'],
    'Pandiangan' => ['Samosir','Pakpahan','Gultom','Sidari','Sitinjak','Harianja'],
    'Aritonang' => ['Ompusunggu','Rajagukguk','Simaremare'],
    'Simatupang' => ['Togatorop','Sianturi','Siburian'],
];

foreach ($indukMap as $indukNama => $subMargas) {
    $stmt = $pdo->prepare("SELECT id FROM marga WHERE nama = ?");
    $stmt->execute([$indukNama]);
    $indukId = $stmt->fetchColumn();
    if (!$indukId) continue;
    foreach ($subMargas as $sub) {
        $pdo->exec("UPDATE marga SET marga_induk_id = {$indukId} WHERE nama = " . $pdo->quote($sub) . " AND marga_induk_id IS NULL");
    }
}

echo "Marga induk links set.\n";
echo "Total marga: " . $pdo->query("SELECT COUNT(*) FROM marga")->fetchColumn() . "\n";
echo "\nPart 1 done. Run part 2 next.\n";
