const API = { history: { getCulturalSites: (params) => fetch(`${API_BASE_URL}/history/cultural-sites?${new URLSearchParams(params)}`).then(r => r.json()), createCulturalSite: (data) => fetch(`${API_BASE_URL}/history/cultural-sites`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${getAuthToken()}` }, body: JSON.stringify(data) }).then(r => r.json()) }, marga: { getAll: () => fetch(`${API_BASE_URL}/marga`).then(r => r.json()) } };
document.addEventListener('DOMContentLoaded', () => { loadSites(); loadMarga(); setupEventListeners(); });
function loadSites() { const params = { tipe: document.getElementById('filterTipe').value, marga_id: document.getElementById('filterMarga').value, status_konservasi: document.getElementById('filterStatus').value }; API.history.getCulturalSites(params).then(response => { if (response.success) renderSites(response.data); }); }
function renderSites(sites) { const container = document.getElementById('sitesList'); if (sites.length === 0) { container.innerHTML = '<p class="text-gray-500 col-span-full text-center py-8">Tidak ada situs budaya</p>'; return; } container.innerHTML = sites.map(s => `<div class="bg-white rounded-lg shadow p-4"><div class="flex justify-between items-start mb-2"><span class="px-2 py-1 text-xs rounded-full ${getTipeColor(s.tipe)}">${formatTipe(s.tipe)}</span><span class="px-2 py-1 text-xs rounded-full ${getStatusColor(s.status_konservasi)}">${formatStatus(s.status_konservasi)}</span></div><h3 class="font-bold text-lg mb-2">${s.nama}</h3><p class="text-gray-600 text-sm mb-2 line-clamp-2">${s.deskripsi || '-'}</p><p class="text-gray-500 text-sm mb-2">📍 ${s.kota || '-'}, ${s.provinsi || '-'}</p>${s.latitude && s.longitude ? `<div class="mt-2 p-2 bg-gray-100 rounded text-xs">🗺️ ${s.latitude}, ${s.longitude}</div>` : ''}</div>`).join(); }
function loadMarga() { API.marga.getAll().then(response => { if (response.success) { const filterMarga = document.getElementById('filterMarga'); const siteMarga = document.getElementById('siteMarga'); const options = response.data.map(m => `<option value="${m.id}">${m.nama}</option>`).join(''); filterMarga.innerHTML = '<option value="">Semua Marga</option>' + options; siteMarga.innerHTML = '<option value="">Tidak ada marga spesifik</option>' + options; } }); }
function setupEventListeners() { document.getElementById('addSiteBtn').addEventListener('click', () => openModal()); document.getElementById('closeModal').addEventListener('click', closeModal); document.getElementById('cancelBtn').addEventListener('click', closeModal); document.getElementById('siteForm').addEventListener('submit', saveSite); document.getElementById('filterTipe').addEventListener('change', loadSites); document.getElementById('filterMarga').addEventListener('change', loadSites); document.getElementById('filterStatus').addEventListener('change', loadSites); }
function openModal() { document.getElementById('siteModal').classList.remove('hidden'); }
function closeModal() { document.getElementById('siteModal').classList.add('hidden'); document.getElementById('siteForm').reset(); }
function saveSite(e) { e.preventDefault(); const data = { nama: document.getElementById('siteNama').value, tipe: document.getElementById('siteTipe').value, deskripsi: document.getElementById('siteDeskripsi').value, alamat: document.getElementById('siteAlamat').value, kota: document.getElementById('siteKota').value, provinsi: document.getElementById('siteProvinsi').value, latitude: document.getElementById('siteLatitude').value || null, longitude: document.getElementById('siteLongitude').value || null, marga_id: document.getElementById('siteMarga').value || null, sejarah: document.getElementById('siteSejarah').value, status_konservasi: document.getElementById('siteStatus').value }; API.history.createCulturalSite(data).then(response => { if (response.success) { Toast.success('Situs budaya berhasil ditambahkan'); closeModal(); loadSites(); } }); }
function formatTipe(tipe) { const types = { 'makam_leluhur': 'Makam Leluhur', 'situs_adat': 'Situs Adat', 'tempat_suci': 'Tempat Suci', 'monumen': 'Monumen' }; return types[tipe] || tipe; }
function formatStatus(status) { const statuses = { 'terjaga': 'Terjaga', 'terancam': 'Terancam', 'rusak': 'Rusak', 'hilang': 'Hilang' }; return statuses[status] || status; }
function getTipeColor(tipe) { const colors = { 'makam_leluhur': 'bg-gray-100 text-gray-800', 'situs_adat': 'bg-purple-100 text-purple-800', 'tempat_suci': 'bg-yellow-100 text-yellow-800', 'monumen': 'bg-blue-100 text-blue-800' }; return colors[tipe] || 'bg-gray-100 text-gray-800'; }
function getStatusColor(status) { const colors = { 'terjaga': 'bg-green-100 text-green-800', 'terancam': 'bg-orange-100 text-orange-800', 'rusak': 'bg-red-100 text-red-800', 'hilang': 'bg-gray-100 text-gray-800' }; return colors[status] || 'bg-gray-100 text-gray-800'; }
