const EventsAPI = { events: { getAll: () => fetch(`${API_BASE_URL}/events`).then(r => r.json()), create: (data) => fetch(`${API_BASE_URL}/events`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${getAuthToken()}` }, body: JSON.stringify(data) }).then(r => r.json()) } };
document.addEventListener('DOMContentLoaded', () => { loadEvents(); setupEventListeners(); });
function loadEvents() { document.getElementById('loadingState').classList.remove('hidden'); EventsAPI.events.getAll().then(response => { if (response.success) { renderEvents(response.data); } }).finally(() => document.getElementById('loadingState').classList.add('hidden')); }
function renderEvents(events) { const container = document.getElementById('eventsList'); if (events.length === 0) { container.innerHTML = '<p class="text-center text-gray-500 py-8">Tidak ada acara</p>'; return; } container.innerHTML = events.map(e => `<div class="bg-white rounded-lg shadow p-4"><div class="flex justify-between items-start"><div><h3 class="font-bold text-lg">${e.judul}</h3><p class="text-gray-600 text-sm">${e.deskripsi || '-'}</p><p class="text-gray-500 text-sm mt-2">📅 ${new Date(e.tanggal_mulai).toLocaleString('id-ID')}</p><p class="text-gray-500 text-sm">📍 ${e.lokasi || '-'}</p></div><span class="px-2 py-1 text-xs rounded-full ${getStatusColor(e.status)}">${formatStatus(e.status)}</span></div></div>`).join(); }
function setupEventListeners() { document.getElementById('addEventBtn').addEventListener('click', () => openModal()); document.getElementById('closeModal').addEventListener('click', closeModal); document.getElementById('cancelBtn').addEventListener('click', closeModal); document.getElementById('eventForm').addEventListener('submit', saveEvent); }
function openModal() { document.getElementById('eventModal').classList.remove('hidden'); }
function closeModal() { document.getElementById('eventModal').classList.add('hidden'); document.getElementById('eventForm').reset(); }
function saveEvent(e) { e.preventDefault(); const data = { judul: document.getElementById('eventJudul').value, tipe: document.getElementById('eventTipe').value, tanggal_mulai: document.getElementById('eventTanggalMulai').value, tanggal_selesai: document.getElementById('eventTanggalSelesai').value, lokasi: document.getElementById('eventLokasi').value, deskripsi: document.getElementById('eventDeskripsi').value }; EventsAPI.events.create(data).then(response => { if (response.success) { Toast.success('Acara berhasil ditambahkan'); closeModal(); loadEvents(); } }); }
function formatStatus(status) { const statuses = { 'terjadwal': 'Terjadwal', 'berlangsung': 'Berlangsung', 'selesai': 'Selesai', 'dibatalkan': 'Dibatalkan' }; return statuses[status] || status; }
function getStatusColor(status) { const colors = { 'terjadwal': 'bg-blue-100 text-blue-800', 'berlangsung': 'bg-green-100 text-green-800', 'selesai': 'bg-gray-100 text-gray-800', 'dibatalkan': 'bg-red-100 text-red-800' }; return colors[status] || 'bg-gray-100 text-gray-800'; }
